### ISSUE TITLE
How to use the sources

### ISSUE THREAD

**Issue by parameterz3p0** [Roboe/TravelerNlpBackend#1]
Hello Roboe :)

I bought a Fairphone 2 last week, and i first want to thank you for the job you do :)
I come from the fairphone forum for playing Pokemon Go without GAPP on OSOS !
I would need your help please : i... don't know how to use github...

How must i compile your sources to build an apk please ? O:)
I'm learning programmation but i still have problem to compile, and the word "flash" is still scaring me ^^
(i was feeling like god when i installed Xposed to spoof signatures and that my phone was still alive... :°)

Thx in advance :)

Parameterz3.0

Edit : I tried to compile with Android Studio.. but i can't. Is it possible to add any repo to F-Droid ?

**Comment by Roboe** [comment]
Hello! Sorry for the delay.

If you have Android Studio installed, it's pretty easy. I'll presume you have already imported the source code. Connect your phone by USB and select the option [Run 'app'] from the [Run] menu. Then select your device (check the authorization pop-up on the screen of your FP2) and [Ok] on Android Studio. If the build fails, check the error in the console --you will probably need to install Lollipop SDK, but it's as far as a click!

If you prefer the command line, just `cd` into the root folder, `chmod +x gradlew` (only first time) and `./gradlew assembleDebug` (or, if you are on Windows, `gradle.bat assembleDebug`) and check the output for errors.

Feel free to contact me via [FP forum private messaging](https://forum.fairphone.com/users/roboe) for more help. I'll close this issue.

PD: Congrats for the FP2 adquisition --take the oportunity to learn, the FP community is wonderful!

**Comment by Roboe** [comment]
If you're still interested, I found a complete and neat guide to compile Android apps easily by the Briar Team: https://briarproject.org/building.html
Just replace the URL by https://github.com/Roboe/TravelerNlpBackend.git on the fourth step. Everything else should be the same, :)
